### Przy pomocy indeksowania wybierz słowo 'kot' z listy

In [ ]:
lista = [1,[2,3],[[6,'kot',7],8],[[4],5,[5,7],9]]

### Stwórz słownik w którym zapiszesz swoje 'imię', 'nazwisko', 'wiek' oraz 'stanowisko w sporze o uniwersalnia' i wyprintuj dowolny element z tego słownika. 

In [ ]:
slownik = ...

### Stwórz funckję, która przyjmuje listę oraz liczbę jako argumenty. Funkcja powinna:
* ### sprawdzać długość listy. Jeśli lista ma już 12 elementów, funkcja ma informować, że jest pełna i zwracać tę samą listę
* ### sprawdzać czy nowa liczba jest już w liście. Jeśli jest, funkcja printuje "Liczba jest już elementem listy" i zwraca listę. Jeśli nie ma, printuje "Liczba dodana" i zwraca listę z dodanym elementem.

In [4]:
import numpy as np

### Stwórz array składający się z 20 zer

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

### Stwórz array 40 liczb w równych odstępach od liczby 3 do 4

array([2.        , 2.02564103, 2.05128205, 2.07692308, 2.1025641 ,
       2.12820513, 2.15384615, 2.17948718, 2.20512821, 2.23076923,
       2.25641026, 2.28205128, 2.30769231, 2.33333333, 2.35897436,
       2.38461538, 2.41025641, 2.43589744, 2.46153846, 2.48717949,
       2.51282051, 2.53846154, 2.56410256, 2.58974359, 2.61538462,
       2.64102564, 2.66666667, 2.69230769, 2.71794872, 2.74358974,
       2.76923077, 2.79487179, 2.82051282, 2.84615385, 2.87179487,
       2.8974359 , 2.92307692, 2.94871795, 2.97435897, 3.        ])

### Wybierz części arraya "arr2d" przy pomocy slicingu według przykładów poniżej

In [16]:
arr2d = np.array([np.arange(10,5,-1),np.arange(10,15),np.arange(0,-5,-1),np.arange(0,5)])
arr2d

array([[10,  9,  8,  7,  6],
       [10, 11, 12, 13, 14],
       [ 0, -1, -2, -3, -4],
       [ 0,  1,  2,  3,  4]])

**array([ 9, 11, -1,  1])**

array([ 9, 11, -1,  1])

**array([[ 8,  7,  6], <br>
  $\;\;\;\;\;\;\;\;$      [12, 13, 14]])**

array([[ 8,  7,  6],
       [12, 13, 14]])

### Policz sumę dla elementów z każdej kolumny arr2d

array([20, 20, 20, 20, 20])

### Stwórz DataFrame zawierający dwie kolumny o nazwach "kolumna A" i "kolumna B" z losowymi danymi. Następnie dołącz trzecią kolumnę, która będzie sumą wartości w wierszach kolumny A i B.

In [33]:
import pandas as pd